apiVersion: v1
kind: Service
metadata:
  name: public-api
spec:
  type: NodePort
  ports:
  - port: 9000
    targetPort: 8000
    nodePort: 31000
    name: "http"
    protocol: TCP
  - port: 443
    targetPort: 4430
    nodePort: 31500
    name: "https"
    protocol: TCP
  selector:
    app: api
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    name: postgres
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 32000
  selector:
    app: database
