apiVersion: v1
kind: Service
metadata:
  name: public-api
spec:
  ports:
  - port: 80
    targetPort: 8000
    name: "http"
    protocol: TCP
  - port: 443
    targetPort: 4430
    name: "https"
    protocol: TCP
  selector:
    app: api
  type: LoadBalancer
