apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: nginx
          image: nginx
        - name: flask
          image: gcr.io/{{USER}}/flask-api:{{VERSION}}
          env:
            - name: DATABASE
              value: postgres
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-master-db
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-master-db
                  key: password
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: session-secret
                  key: session-secret
